### ISSUE TITLE
The lib works fine, but have a memory leak in events

### ISSUE THREAD

**Issue by karacas** [fcannizzaro/win-audio#10]
![image](https://user-images.githubusercontent.com/1050937/90297909-8fdedf80-de66-11ea-9998-d6dc4a8ec1ff.png)

**Comment by Nealsoni00** [comment]
Was wondering if you found any solution to the memory leak, I've been experiencing a similar leak.

Alternatively, is there another library that lets you set system volume in node without a leak?

**Comment by Nealsoni00** [comment]
@karacas How were you able to determine memory usage over an extended period of time? I'm having trouble getting a profiler to attach to the main node process.

**Comment by adriencarbonaro** [comment]
+1
