### ISSUE TITLE
Can't import the package

### ISSUE THREAD

**Issue by Emilijus436** [fcannizzaro/win-audio#13]
When I try to import the package, I get `Error: Could not locate the bindings file.`

**Comment by fcannizzaro** [comment]
I messed up the package files (a typo on bindings file)

**Comment by Jiangzy520** [comment]
> 当我尝试导入包时，我得到 `Error: Could not locate the bindings file.`

Sir, can I get an email address? I would like to consult with you.

**Comment by Emilijus436** [comment]
> > 当我尝试导入包时，我得到 `Error: Could not locate the bindings file.`
> 
> Sir, can I get an email address? I would like to consult with you.

My email address is [emilijusbanikonis20@gmail.com](url).

**Comment by Jiangzy520** [comment]
> > > 当我尝试导入包时，我得到  `Error: Could not locate the bindings file.`
> > 
> > 
> > 先生，可以给我一个电子邮件地址吗？  我想向您咨询一下。
> 
> 我的电子邮件地址是 [emilijusbanikonis20@gmail.com ](url) 。

Send a question and hope to hear from you.
