### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ServerDeveloper9447** [fcannizzaro/win-audio#15]
Speaker control functions
speaker.mute()
speaker.unmute()
speaker.set()
speaker.increase()
speaker.decrease()

not working at all

**Comment by fcannizzaro** [comment]
can you try the [`3.0.5`](https://www.npmjs.com/package/win-audio/v/3.0.5) version ?

**Comment by ServerDeveloper9447** [comment]
It works now. Thank you
