### ISSUE TITLE
Mute toggle event not called

### ISSUE THREAD

**Issue by 21repierre** [fcannizzaro/win-audio#8]
The 'toggle' event is not being called when `audio.toggle()` is called nor when I mute the speaker from windows itself

My code: `this.device.events.on('toggle', (status) => {
			console.log(status);
			thiz.muted = status.new;
		});`

**Comment by fcannizzaro** [comment]
This is strange😕, I tested this case now and toggle events were emitted using Windows mixer toggle. Any news ?

**Comment by fcannizzaro** [comment]
Did you setup a [polling rate](https://github.com/fcannizzaro/win-audio#pollinginterval-int--500) ? 
```javascript
this.device.polling(200);
```
